### PR TITLE
Complex valued periodic constraint (scale)

### PR DESCRIPTION
**Pull request by jorgensd**
@conpierce8  Could you try this branch for your work? 
I've added in complex types in the places where I think its needed, but maybe there are more places which I've missed.

Try fixing #33

### CODE REVIEW

**Comment by jorgensd** [comment]
@conpierce8 some things werent picked up on my system. Ill fix them tomorrow and let you know when the pipeline is green

**Comment by conpierce8** [comment]
My impression from looking through the source code was that [`apply_lifting`](https://github.com/jorgensd/dolfinx_mpc/blob/dokken/complex-periodic/python/dolfinx_mpc/mpc.cpp#L205) might need the same treatment.

**Comment by conpierce8** [comment]
Also not sure if this request should be part of the same issue or if I should open a new issue/feature request: in the wave propagation context with complex scale factors, it's also usual to pre-multiply by the _Hermitian_ transpose of the prolongation matrix rather than the regular transpose:
$$K^H A K = K^H b$$
This way the matrix $K^H A K$ is Hermitian if $A$ is also Hermitian. I'm not sure where in the code that would need to be implemented, and if you would want to allow users to choose between $K^T$ and $K^H$.

**Comment by jorgensd** [comment]
> Also not sure if this request should be part of the same issue or if I should open a new issue/feature request: in the wave propagation context with complex scale factors, it's also usual to pre-multiply by the _Hermitian_ transpose of the prolongation matrix rather than the regular transpose: KHAK=KHb This way the matrix KHAK is Hermitian if A is also Hermitian. I'm not sure where in the code that would need to be implemented, and if you would want to allow users to choose between KT and KH.

I would like that to be a separate issue/pull request, as it is not directly related to the issue in this PR.

**Comment by jorgensd** [comment]
@conpierce8 could you test now?:)

**Comment by jorgensd** [comment]
> My impression from looking through the source code was that [`apply_lifting`](https://github.com/jorgensd/dolfinx_mpc/blob/dokken/complex-periodic/python/dolfinx_mpc/mpc.cpp#L205) and `lifting.h` (e.g. [here](https://github.com/jorgensd/dolfinx_mpc/blob/main/cpp/lifting.h#L147), [here](https://github.com/jorgensd/dolfinx_mpc/blob/main/cpp/lifting.h#L425), and [here](https://github.com/jorgensd/dolfinx_mpc/blob/main/cpp/lifting.h#L478)) might need the same treatment.

The scale in lifting is not really used for MPCs, as it is mostly used in Newton-solvers.

**Comment by conpierce8** [comment]
> @conpierce8 could you test now?:)

Tested this morning:

- There is no longer a warning about conversion from complex to real.
- The mass matrix assembled with `dolfinx_mpc` matches the mass matrix computed using manually-constructed prolongation matrices. This fixes #33.

**Pull request merged**
